### ISSUE TITLE
项目中似乎缺少了一些.obj文件

### ISSUE THREAD

**Issue by beiyangU** [YinZhuoyi-NJUST/SFM-from-Circular-Coded-Target-module#1]
您好作者，冒昧打扰，您的项目非常吸引我，最近在复现您的代码，但VS报错在本项目的Matlab2C文件夹下缺少了如下文件：halideRuntime.obj、morphop2_halide_imdilate_float32_host.obj和morphop2_halide_imerode_float32_host.obj，复现工作对我十分重要，诚恳希望您能向我分享这些文件，我的邮箱是1968422534@qq.com，不胜感激！祝好！

**Comment by YinZhuoyi-NJUST** [comment]
fixed
